### ISSUE TITLE
When mutations fire in sync, only the last one sticks

### ISSUE THREAD

**Issue by tteke** [dandevs/mobx-async-intercept#1]
An example:

```javascript
const test = mobx.observable({
  key1: 'value1',
  key2: 'value2',
});

interceptAsync(test, (changes) => {
  return Promise.resolve(changes)
})

test.key1 = 'value1updated';
test.key2 = 'value2updated';
test.key3 = 'value3';

// results in test => { key1: 'value1', key2: 'value2', key3: 'value3' }
```

**Comment by tteke** [comment]
Just saw the tests, it seems that it was intentional, but should it?
Maybe the interceptor should delay each mutation's promise until the active one finishes.

**Comment by dandevs** [comment]
This is happening because `Promise.resolve().then()` does not actually execute synchronously and ends up discarding the "unresolved intercepts". In the case of `observable.object/array` I can change this behavior to a per key basis rather than the whole object.

**Comment by tteke** [comment]
Yea I figured that was happening. Imo, it should discard unresolved intercepts per key basis as you suggested, otherwise it should chain the changes to the activePromise if there is one.

**Comment by dandevs** [comment]
Sorry for the delay! If you need chaining of the `activePromise` just shoot and I'll be more than happy to implement that for you.
